compat.syntaxVersion=3
compat.version=20260818
compat.name=Solaris (tagged BSD style)
compat.description=Parser and formatter for compatibility with the tagged "digest -v -a <algo>" call on Solaris
compat.authors=Johann N. Löfflmann <https://johann.loefflmann.net>

algorithm.default=sha3-256
algorithm.userSelectable=true

parser.ignoreLinesStartingWithString=#
parser.ignoreEmptyLines=false

parser.regexp=^([\\\\]?)([^ ]+) \\((.+)\\) = ([a-z0-9]{#NIBBLES})$
parser.regexp.gnuEscapingPos=1
parser.regexp.algonamePos=2
parser.regexp.filenamePos=3
parser.regexp.hashPos=4
parser.regexp.nibbles=64

formatter.format=#ESCAPETAG#ALGONAME (#FILENAME) = #DIGEST{hex}
formatter.hash.encoding=hex
formatter.lineSeparator=\n
formatter.gnuescaping.enabled=false
formatter.gnuescaping.userSelectable=true

# The algorithm names that "digest -v" prints on Solaris do not always match the
# lowercased name of the algorithm in Jacksum, the names of the SHA family are
# printed without a hyphen for example:
# sha256 (foobar) = ca9781...

formatter.ALGONAME.defaultReplacement=#ALGONAME{lowercase}
formatter.ALGONAME.exceptionMappings=\
sha-1=sha1;\
sha-224=sha224;\
sha-256=sha256;\
sha-384=sha384;\
sha-512=sha512
